<?php

return [
    'api_key' => env('RAJAONGKIR_API_KEY', ''),
    'api_shipping_delivery_key' => env('RAJAONGKIR_API_SHIPPING_DELIVERY_KEY', ''),
    
    'provinces' => [
        ['id' => 1, 'name' => 'NUSA TENGGARA BARAT (NTB)'],
        ['id' => 2, 'name' => 'MALUKU'],
        ['id' => 3, 'name' => 'KALIMANTAN SELATAN'],
        ['id' => 4, 'name' => 'KALIMANTAN TENGAH'],
        ['id' => 5, 'name' => 'JAWA BARAT'],
        ['id' => 6, 'name' => 'BENGKULU'],
        ['id' => 7, 'name' => 'KALIMANTAN TIMUR'],
        ['id' => 8, 'name' => 'KEPULAUAN RIAU'],
        ['id' => 9, 'name' => 'NANGGROE ACEH DARUSSALAM (NAD)'],
        ['id' => 10, 'name' => 'DKI JAKARTA'],
        ['id' => 11, 'name' => 'BANTEN'],
        ['id' => 12, 'name' => 'JAWA TENGAH'],
        ['id' => 13, 'name' => 'JAMBI'],
        ['id' => 14, 'name' => 'PAPUA'],
        ['id' => 15, 'name' => 'BALI'],
        ['id' => 16, 'name' => 'SUMATERA UTARA'],
        ['id' => 17, 'name' => 'GORONTALO'],
        ['id' => 18, 'name' => 'JAWA TIMUR'],
        ['id' => 19, 'name' => 'DI YOGYAKARTA'],
        ['id' => 20, 'name' => 'SULAWESI TENGGARA'],
        ['id' => 21, 'name' => 'NUSA TENGGARA TIMUR (NTT)'],
        ['id' => 22, 'name' => 'SULAWESI UTARA'],
        ['id' => 23, 'name' => 'SUMATERA BARAT'],
        ['id' => 24, 'name' => 'BANGKA BELITUNG'],
        ['id' => 25, 'name' => 'RIAU'],
        ['id' => 26, 'name' => 'SUMATERA SELATAN'],
        ['id' => 27, 'name' => 'SULAWESI TENGAH'],
        ['id' => 28, 'name' => 'KALIMANTAN BARAT'],
        ['id' => 29, 'name' => 'PAPUA BARAT'],
        ['id' => 30, 'name' => 'LAMPUNG'],
        ['id' => 31, 'name' => 'KALIMANTAN UTARA'],
        ['id' => 32, 'name' => 'MALUKU UTARA'],
        ['id' => 33, 'name' => 'SULAWESI SELATAN'],
        ['id' => 34, 'name' => 'SULAWESI BARAT'],
    ],

    'cities' => [
        ['id' => 1, 'province_id' => 1, 'name' => 'MATARAM'],
        ['id' => 2, 'province_id' => 1, 'name' => 'BIMA'],
        ['id' => 3, 'province_id' => 1, 'name' => 'DOMPU'],
        ['id' => 4, 'province_id' => 1, 'name' => 'LOMBOK TENGAH'],
        ['id' => 5, 'province_id' => 1, 'name' => 'LOMBOK TIMUR'],
        ['id' => 7, 'province_id' => 1, 'name' => 'SUMBAWA'],
        ['id' => 8, 'province_id' => 1, 'name' => 'LOMBOK BARAT'],
        ['id' => 9, 'province_id' => 1, 'name' => 'LOMBOK UTARA'],
        ['id' => 10, 'province_id' => 1, 'name' => 'SUMBAWA BARAT'],
        ['id' => 11, 'province_id' => 2, 'name' => 'AMBON'],
        ['id' => 12, 'province_id' => 2, 'name' => 'MALUKU TENGAH'],
        ['id' => 14, 'province_id' => 2, 'name' => 'MALUKU TENGGARA'],
        ['id' => 15, 'province_id' => 2, 'name' => 'TUAL'],
        ['id' => 16, 'province_id' => 2, 'name' => 'BURU'],
        ['id' => 17, 'province_id' => 2, 'name' => 'BURU SELATAN'],
        ['id' => 19, 'province_id' => 2, 'name' => 'KEPULAUAN ARU'],
        ['id' => 21, 'province_id' => 2, 'name' => 'SERAM BAGIAN BARAT'],
        ['id' => 23, 'province_id' => 2, 'name' => 'SERAM BAGIAN TIMUR'],
        ['id' => 24, 'province_id' => 2, 'name' => 'MALUKU BARAT DAYA'],
        ['id' => 25, 'province_id' => 2, 'name' => 'MALUKU TENGGARA BARAT'],
        ['id' => 29, 'province_id' => 3, 'name' => 'BANJARMASIN'],
        ['id' => 30, 'province_id' => 3, 'name' => 'HULU SUNGAI TENGAH'],
        ['id' => 32, 'province_id' => 3, 'name' => 'HULU SUNGAI SELATAN'],
        ['id' => 34, 'province_id' => 3, 'name' => 'KOTABARU'],
        ['id' => 35, 'province_id' => 3, 'name' => 'TABALONG'],
        ['id' => 36, 'province_id' => 3, 'name' => 'BANJARBARU'],
        ['id' => 38, 'province_id' => 3, 'name' => 'HULU SUNGAI UTARA'],
        ['id' => 39, 'province_id' => 3, 'name' => 'BARITO KUALA'],
        ['id' => 40, 'province_id' => 3, 'name' => 'BANJAR'],
        ['id' => 42, 'province_id' => 3, 'name' => 'TANAH LAUT'],
        ['id' => 44, 'province_id' => 3, 'name' => 'TAPIN'],
        ['id' => 53, 'province_id' => 3, 'name' => 'BALANGAN'],
        ['id' => 54, 'province_id' => 3, 'name' => 'TANAH BUMBU'],
        ['id' => 46, 'province_id' => 4, 'name' => 'BARITO UTARA'],
        ['id' => 48, 'province_id' => 4, 'name' => 'BARITO TIMUR'],
        ['id' => 50, 'province_id' => 4, 'name' => 'MURUNG RAYA'],
        ['id' => 52, 'province_id' => 4, 'name' => 'BARITO SELATAN'],
        ['id' => 456, 'province_id' => 4, 'name' => 'PALANGKA RAYA'],
        ['id' => 458, 'province_id' => 4, 'name' => 'KATINGAN'],
        ['id' => 460, 'province_id' => 4, 'name' => 'KAPUAS'],
        ['id' => 462, 'province_id' => 4, 'name' => 'GUNUNG MAS'],
        ['id' => 464, 'province_id' => 4, 'name' => 'SERUYAN'],
        ['id' => 466, 'province_id' => 4, 'name' => 'KOTAWARINGIN BARAT'],
        ['id' => 468, 'province_id' => 4, 'name' => 'KOTAWARINGIN TIMUR'],
        ['id' => 470, 'province_id' => 4, 'name' => 'LAMANDAU'],
        ['id' => 471, 'province_id' => 4, 'name' => 'PULANG PISAU'],
        ['id' => 472, 'province_id' => 4, 'name' => 'SUKAMARA'],
        ['id' => 55, 'province_id' => 5, 'name' => 'BANDUNG'],
        ['id' => 56, 'province_id' => 5, 'name' => 'CIMAHI'],
        ['id' => 57, 'province_id' => 5, 'name' => 'SUMEDANG'],
        ['id' => 59, 'province_id' => 5, 'name' => 'GARUT'],
        ['id' => 60, 'province_id' => 5, 'name' => 'BANDUNG BARAT'],
        ['id' => 62, 'province_id' => 5, 'name' => 'CIANJUR'],
        ['id' => 63, 'province_id' => 5, 'name' => 'BEKASI'],
        ['id' => 77, 'province_id' => 5, 'name' => 'BOGOR'],
        ['id' => 129, 'province_id' => 5, 'name' => 'CIREBON'],
        ['id' => 131, 'province_id' => 5, 'name' => 'INDRAMAYU'],
        ['id' => 132, 'province_id' => 5, 'name' => 'KUNINGAN'],
        ['id' => 133, 'province_id' => 5, 'name' => 'MAJALENGKA'],
        ['id' => 199, 'province_id' => 5, 'name' => 'DEPOK'],
        ['id' => 329, 'province_id' => 5, 'name' => 'KARAWANG'],
        ['id' => 532, 'province_id' => 5, 'name' => 'PURWAKARTA'],
        ['id' => 533, 'province_id' => 5, 'name' => 'SUBANG'],
        ['id' => 538, 'province_id' => 5, 'name' => 'SUKABUMI'],
        ['id' => 632, 'province_id' => 5, 'name' => 'TASIKMALAYA'],
        ['id' => 633, 'province_id' => 5, 'name' => 'BANJAR'],
        ['id' => 634, 'province_id' => 5, 'name' => 'CIAMIS'],
        ['id' => 635, 'province_id' => 5, 'name' => 'PANGANDARAN'],
        ['id' => 64, 'province_id' => 6, 'name' => 'BENGKULU'],
        ['id' => 65, 'province_id' => 6, 'name' => 'BENGKULU UTARA'],
        ['id' => 66, 'province_id' => 6, 'name' => 'BENGKULU TENGAH'],
        ['id' => 67, 'province_id' => 6, 'name' => 'REJANG LEBONG'],
        ['id' => 68, 'province_id' => 6, 'name' => 'BENGKULU SELATAN'],
        ['id' => 69, 'province_id' => 6, 'name' => 'KAUR'],
        ['id' => 70, 'province_id' => 6, 'name' => 'KEPAHIANG'],
        ['id' => 71, 'province_id' => 6, 'name' => 'LEBONG'],
        ['id' => 73, 'province_id' => 6, 'name' => 'MUKO MUKO'],
        ['id' => 76, 'province_id' => 6, 'name' => 'SELUMA'],
        ['id' => 78, 'province_id' => 7, 'name' => 'BALIKPAPAN'],
        ['id' => 79, 'province_id' => 7, 'name' => 'KUTAI KARTANEGARA'],
        ['id' => 80, 'province_id' => 7, 'name' => 'PASER'],
        ['id' => 81, 'province_id' => 7, 'name' => 'BERAU'],
        ['id' => 83, 'province_id' => 7, 'name' => 'PENAJAM PASER UTARA'],
        ['id' => 84, 'province_id' => 7, 'name' => 'BONTANG'],
        ['id' => 86, 'province_id' => 7, 'name' => 'KUTAI TIMUR'],
        ['id' => 534, 'province_id' => 7, 'name' => 'SAMARINDA'],
        ['id' => 536, 'province_id' => 7, 'name' => 'KUTAI BARAT'],
        ['id' => 537, 'province_id' => 7, 'name' => 'MAHAKAM ULU'],
        ['id' => 90, 'province_id' => 8, 'name' => 'BATAM'],
        ['id' => 92, 'province_id' => 8, 'name' => 'LINGGA'],
        ['id' => 94, 'province_id' => 8, 'name' => 'NATUNA'],
        ['id' => 95, 'province_id' => 8, 'name' => 'KEPULAUAN ANAMBAS'],
        ['id' => 96, 'province_id' => 8, 'name' => 'KARIMUN'],
        ['id' => 619, 'province_id' => 8, 'name' => 'TANJUNG PINANG'],
        ['id' => 624, 'province_id' => 8, 'name' => 'BINTAN'],
        ['id' => 97, 'province_id' => 9, 'name' => 'BANDA ACEH'],
        ['id' => 98, 'province_id' => 9, 'name' => 'LANGSA'],
        ['id' => 100, 'province_id' => 9, 'name' => 'LHOKSEUMAWE'],
        ['id' => 101, 'province_id' => 9, 'name' => 'ACEH BESAR'],
        ['id' => 102, 'province_id' => 9, 'name' => 'BIREUEN'],
        ['id' => 104, 'province_id' => 9, 'name' => 'ACEH TENGGARA'],
        ['id' => 106, 'province_id' => 9, 'name' => 'ACEH BARAT'],
        ['id' => 107, 'province_id' => 9, 'name' => 'PIDIE'],
        ['id' => 109, 'province_id' => 9, 'name' => 'ACEH TENGAH'],
        ['id' => 110, 'province_id' => 9, 'name' => 'ACEH SELATAN'],
        ['id' => 111, 'province_id' => 9, 'name' => 'SABANG'],
        ['id' => 112, 'province_id' => 9, 'name' => 'ACEH BARAT DAYA'],
        ['id' => 113, 'province_id' => 9, 'name' => 'ACEH JAYA'],
        ['id' => 114, 'province_id' => 9, 'name' => 'ACEH SINGKIL'],
        ['id' => 116, 'province_id' => 9, 'name' => 'ACEH TAMIANG'],
        ['id' => 117, 'province_id' => 9, 'name' => 'ACEH TIMUR'],
        ['id' => 118, 'province_id' => 9, 'name' => 'ACEH UTARA'],
        ['id' => 120, 'province_id' => 9, 'name' => 'BENER MERIAH'],
        ['id' => 122, 'province_id' => 9, 'name' => 'GAYO LUES'],
        ['id' => 124, 'province_id' => 9, 'name' => 'NAGAN RAYA'],
        ['id' => 125, 'province_id' => 9, 'name' => 'PIDIE JAYA'],
        ['id' => 127, 'province_id' => 9, 'name' => 'SIMEULUE'],
        ['id' => 128, 'province_id' => 9, 'name' => 'SUBULUSSALAM'],
        ['id' => 135, 'province_id' => 10, 'name' => 'JAKARTA BARAT'],
        ['id' => 136, 'province_id' => 10, 'name' => 'JAKARTA SELATAN'],
        ['id' => 137, 'province_id' => 10, 'name' => 'JAKARTA PUSAT'],
        ['id' => 138, 'province_id' => 10, 'name' => 'JAKARTA UTARA'],
        ['id' => 139, 'province_id' => 10, 'name' => 'JAKARTA TIMUR'],
        ['id' => 141, 'province_id' => 10, 'name' => 'KEPULAUAN SERIBU'],
        ['id' => 143, 'province_id' => 11, 'name' => 'CILEGON'],
        ['id' => 144, 'province_id' => 11, 'name' => 'PANDEGLANG'],
        ['id' => 147, 'province_id' => 11, 'name' => 'LEBAK'],
        ['id' => 148, 'province_id' => 11, 'name' => 'SERANG'],
        ['id' => 592, 'province_id' => 11, 'name' => 'TANGERANG'],
        ['id' => 594, 'province_id' => 11, 'name' => 'TANGERANG SELATAN'],
        ['id' => 149, 'province_id' => 12, 'name' => 'CILACAP'],
        ['id' => 383, 'province_id' => 12, 'name' => 'MAGELANG'],
        ['id' => 384, 'province_id' => 12, 'name' => 'KEBUMEN'],
        ['id' => 385, 'province_id' => 12, 'name' => 'WONOSOBO'],
        ['id' => 386, 'province_id' => 12, 'name' => 'PURWOREJO'],
        ['id' => 387, 'province_id' => 12, 'name' => 'TEMANGGUNG'],
        ['id' => 539, 'province_id' => 12, 'name' => 'SURAKARTA'],
        ['id' => 540, 'province_id' => 12, 'name' => 'BOYOLALI'],
        ['id' => 541, 'province_id' => 12, 'name' => 'KARANGANYAR'],
        ['id' => 542, 'province_id' => 12, 'name' => 'KLATEN'],
        ['id' => 543, 'province_id' => 12, 'name' => 'SRAGEN'],
        ['id' => 544, 'province_id' => 12, 'name' => 'SUKOHARJO'],
        ['id' => 545, 'province_id' => 12, 'name' => 'WONOGIRI'],
        ['id' => 560, 'province_id' => 12, 'name' => 'SEMARANG'],
        ['id' => 561, 'province_id' => 12, 'name' => 'JEPARA'],
        ['id' => 562, 'province_id' => 12, 'name' => 'KUDUS'],
        ['id' => 563, 'province_id' => 12, 'name' => 'PEKALONGAN'],
        ['id' => 564, 'province_id' => 12, 'name' => 'BATANG'],
        ['id' => 565, 'province_id' => 12, 'name' => 'BLORA'],
        ['id' => 567, 'province_id' => 12, 'name' => 'DEMAK'],
        ['id' => 568, 'province_id' => 12, 'name' => 'KENDAL'],
        ['id' => 569, 'province_id' => 12, 'name' => 'PATI'],
        ['id' => 570, 'province_id' => 12, 'name' => 'PEMALANG'],
        ['id' => 571, 'province_id' => 12, 'name' => 'GROBOGAN'],
        ['id' => 572, 'province_id' => 12, 'name' => 'REMBANG'],
        ['id' => 573, 'province_id' => 12, 'name' => 'SALATIGA'],
        ['id' => 575, 'province_id' => 12, 'name' => 'PURBALINGGA'],
        ['id' => 576, 'province_id' => 12, 'name' => 'BANJARNEGARA'],
        ['id' => 588, 'province_id' => 12, 'name' => 'TEGAL'],
        ['id' => 589, 'province_id' => 12, 'name' => 'BREBES'],
        ['id' => 591, 'province_id' => 12, 'name' => 'BANYUMAS'],
        ['id' => 150, 'province_id' => 13, 'name' => 'JAMBI'],
        ['id' => 152, 'province_id' => 13, 'name' => 'TANJUNG JABUNG BARAT'],
        ['id' => 153, 'province_id' => 13, 'name' => 'MERANGIN'],
        ['id' => 154, 'province_id' => 13, 'name' => 'BATANG HARI'],
        ['id' => 156, 'province_id' => 13, 'name' => 'BUNGO'],
        ['id' => 157, 'province_id' => 13, 'name' => 'SUNGAIPENUH'],
        ['id' => 158, 'province_id' => 13, 'name' => 'KERINCI'],
        ['id' => 160, 'province_id' => 13, 'name' => 'MUARO JAMBI'],
        ['id' => 161, 'province_id' => 13, 'name' => 'SAROLANGUN'],
        ['id' => 163, 'province_id' => 13, 'name' => 'TANJUNG JABUNG TIMUR'],
        ['id' => 164, 'province_id' => 13, 'name' => 'TEBO'],
        ['id' => 165, 'province_id' => 14, 'name' => 'JAYAPURA'],
        ['id' => 166, 'province_id' => 14, 'name' => 'BIAK NUMFOR'],
        ['id' => 167, 'province_id' => 14, 'name' => 'MERAUKE'],
        ['id' => 168, 'province_id' => 14, 'name' => 'NABIRE'],
        ['id' => 169, 'province_id' => 14, 'name' => 'DOGIYAI'],
        ['id' => 171, 'province_id' => 14, 'name' => 'KEPULAUAN YAPEN'],
        ['id' => 172, 'province_id' => 14, 'name' => 'JAYAWIJAYA'],
        ['id' => 174, 'province_id' => 14, 'name' => 'LANNY JAYA'],
        ['id' => 175, 'province_id' => 14, 'name' => 'YALIMO'],
        ['id' => 176, 'province_id' => 14, 'name' => 'NDUGA'],
        ['id' => 177, 'province_id' => 14, 'name' => 'MAMBERAMO TENGAH'],
        ['id' => 178, 'province_id' => 14, 'name' => 'ASMAT'],
        ['id' => 180, 'province_id' => 14, 'name' => 'BOVEN DIGOEL'],
        ['id' => 181, 'province_id' => 14, 'name' => 'KEEROM'],
        ['id' => 183, 'province_id' => 14, 'name' => 'MAPPI'],
        ['id' => 184, 'province_id' => 14, 'name' => 'INTAN JAYA'],
        ['id' => 185, 'province_id' => 14, 'name' => 'PANIAI'],
        ['id' => 186, 'province_id' => 14, 'name' => 'DEIYAI'],
        ['id' => 187, 'province_id' => 14, 'name' => 'PEGUNUNGAN BINTANG'],
        ['id' => 188, 'province_id' => 14, 'name' => 'PUNCAK JAYA'],
        ['id' => 189, 'province_id' => 14, 'name' => 'PUNCAK'],
        ['id' => 190, 'province_id' => 14, 'name' => 'SARMI'],
        ['id' => 192, 'province_id' => 14, 'name' => 'SUPIORI'],
        ['id' => 193, 'province_id' => 14, 'name' => 'TOLIKARA'],
        ['id' => 195, 'province_id' => 14, 'name' => 'WAROPEN'],
        ['id' => 196, 'province_id' => 14, 'name' => 'YAHUKIMO'],
        ['id' => 198, 'province_id' => 14, 'name' => 'MAMBERAMO RAYA'],
        ['id' => 595, 'province_id' => 14, 'name' => 'MIMIKA'],
        ['id' => 201, 'province_id' => 15, 'name' => 'DENPASAR'],
        ['id' => 203, 'province_id' => 15, 'name' => 'KARANGASEM'],
        ['id' => 204, 'province_id' => 15, 'name' => 'BANGLI'],
        ['id' => 205, 'province_id' => 15, 'name' => 'GIANYAR'],
        ['id' => 206, 'province_id' => 15, 'name' => 'JEMBRANA'],
        ['id' => 208, 'province_id' => 15, 'name' => 'KLUNGKUNG'],
        ['id' => 210, 'province_id' => 15, 'name' => 'BULELENG'],
        ['id' => 211, 'province_id' => 15, 'name' => 'TABANAN'],
        ['id' => 212, 'province_id' => 15, 'name' => 'BADUNG'],
        ['id' => 218, 'province_id' => 16, 'name' => 'TOBA SAMOSIR'],
        ['id' => 219, 'province_id' => 16, 'name' => 'GUNUNGSITOLI'],
        ['id' => 220, 'province_id' => 16, 'name' => 'NIAS'],
        ['id' => 221, 'province_id' => 16, 'name' => 'NIAS BARAT'],
        ['id' => 222, 'province_id' => 16, 'name' => 'NIAS SELATAN'],
        ['id' => 223, 'province_id' => 16, 'name' => 'NIAS UTARA'],
        ['id' => 225, 'province_id' => 16, 'name' => 'SIBOLGA'],
        ['id' => 226, 'province_id' => 16, 'name' => 'TAPANULI TENGAH'],
        ['id' => 227, 'province_id' => 16, 'name' => 'PADANG SIDEMPUAN'],
        ['id' => 228, 'province_id' => 16, 'name' => 'TAPANULI SELATAN'],
        ['id' => 229, 'province_id' => 16, 'name' => 'TAPANULI UTARA'],
        ['id' => 231, 'province_id' => 16, 'name' => 'PADANG LAWAS UTARA'],
        ['id' => 239, 'province_id' => 16, 'name' => 'HUMBANG HASUNDUTAN'],
        ['id' => 240, 'province_id' => 16, 'name' => 'MANDAILING NATAL'],
        ['id' => 243, 'province_id' => 16, 'name' => 'PADANG LAWAS'],
        ['id' => 361, 'province_id' => 16, 'name' => 'MEDAN'],
        ['id' => 363, 'province_id' => 16, 'name' => 'ASAHAN'],
        ['id' => 364, 'province_id' => 16, 'name' => 'DAIRI'],
        ['id' => 365, 'province_id' => 16, 'name' => 'DELI SERDANG'],
        ['id' => 366, 'province_id' => 16, 'name' => 'BINJAI'],
        ['id' => 368, 'province_id' => 16, 'name' => 'SIMALUNGUN'],
        ['id' => 370, 'province_id' => 16, 'name' => 'LABUHANBATU UTARA'],
        ['id' => 371, 'province_id' => 16, 'name' => 'LABUHANBATU'],
        ['id' => 372, 'province_id' => 16, 'name' => 'LABUHANBATU SELATAN'],
        ['id' => 374, 'province_id' => 16, 'name' => 'KARO'],
        ['id' => 375, 'province_id' => 16, 'name' => 'LANGKAT'],
        ['id' => 376, 'province_id' => 16, 'name' => 'SERDANG BEDAGAI'],
        ['id' => 377, 'province_id' => 16, 'name' => 'TEBING TINGGI'],
        ['id' => 378, 'province_id' => 16, 'name' => 'BATU BARA'],
        ['id' => 379, 'province_id' => 16, 'name' => 'PAKPAK BHARAT'],
        ['id' => 380, 'province_id' => 16, 'name' => 'SAMOSIR'],
        ['id' => 381, 'province_id' => 16, 'name' => 'TANJUNG BALAI'],
        ['id' => 382, 'province_id' => 16, 'name' => 'PEMATANG SIANTAR'],
        ['id' => 251, 'province_id' => 17, 'name' => 'GORONTALO'],
        ['id' => 252, 'province_id' => 17, 'name' => 'GORONTALO UTARA'],
        ['id' => 253, 'province_id' => 17, 'name' => 'BOALEMO'],
        ['id' => 254, 'province_id' => 17, 'name' => 'BONE BOLANGO'],
        ['id' => 255, 'province_id' => 17, 'name' => 'POHUWATO'],
        ['id' => 256, 'province_id' => 18, 'name' => 'JEMBER'],
        ['id' => 257, 'province_id' => 18, 'name' => 'BANYUWANGI'],
        ['id' => 258, 'province_id' => 18, 'name' => 'BONDOWOSO'],
        ['id' => 289, 'province_id' => 18, 'name' => 'KEDIRI'],
        ['id' => 353, 'province_id' => 18, 'name' => 'MADIUN'],
        ['id' => 355, 'province_id' => 18, 'name' => 'MAGETAN'],
        ['id' => 357, 'province_id' => 18, 'name' => 'NGAWI'],
        ['id' => 359, 'province_id' => 18, 'name' => 'PACITAN'],
        ['id' => 360, 'province_id' => 18, 'name' => 'PONOROGO'],
        ['id' => 388, 'province_id' => 18, 'name' => 'MOJOKERTO'],
        ['id' => 389, 'province_id' => 18, 'name' => 'JOMBANG'],
        ['id' => 390, 'province_id' => 18, 'name' => 'NGANJUK'],
        ['id' => 391, 'province_id' => 18, 'name' => 'MALANG'],
        ['id' => 392, 'province_id' => 18, 'name' => 'BLITAR'],
        ['id' => 393, 'province_id' => 18, 'name' => 'BATU'],
        ['id' => 394, 'province_id' => 18, 'name' => 'PROBOLINGGO'],
        ['id' => 395, 'province_id' => 18, 'name' => 'LUMAJANG'],
        ['id' => 396, 'province_id' => 18, 'name' => 'SITUBONDO'],
        ['id' => 531, 'province_id' => 18, 'name' => 'PASURUAN'],
        ['id' => 566, 'province_id' => 18, 'name' => 'BOJONEGORO'],
        ['id' => 577, 'province_id' => 18, 'name' => 'SURABAYA'],
        ['id' => 578, 'province_id' => 18, 'name' => 'GRESIK'],
        ['id' => 579, 'province_id' => 18, 'name' => 'LAMONGAN'],
        ['id' => 580, 'province_id' => 18, 'name' => 'BANGKALAN'],
        ['id' => 581, 'province_id' => 18, 'name' => 'PAMEKASAN'],
        ['id' => 582, 'province_id' => 18, 'name' => 'SAMPANG'],
        ['id' => 583, 'province_id' => 18, 'name' => 'SIDOARJO'],
        ['id' => 584, 'province_id' => 18, 'name' => 'SUMENEP'],
        ['id' => 585, 'province_id' => 18, 'name' => 'TUBAN'],
        ['id' => 586, 'province_id' => 18, 'name' => 'TULUNGAGUNG'],
        ['id' => 587, 'province_id' => 18, 'name' => 'TRENGGALEK'],
        ['id' => 259, 'province_id' => 19, 'name' => 'YOGYAKARTA'],
        ['id' => 260, 'province_id' => 19, 'name' => 'BANTUL'],
        ['id' => 261, 'province_id' => 19, 'name' => 'SLEMAN'],
        ['id' => 262, 'province_id' => 19, 'name' => 'KULON PROGO'],
        ['id' => 263, 'province_id' => 19, 'name' => 'GUNUNG KIDUL'],
        ['id' => 264, 'province_id' => 20, 'name' => 'KENDARI'],
        ['id' => 267, 'province_id' => 20, 'name' => 'BAU-BAU'],
        ['id' => 268, 'province_id' => 20, 'name' => 'KOLAKA'],
        ['id' => 269, 'province_id' => 20, 'name' => 'KOLAKA TIMUR'],
        ['id' => 271, 'province_id' => 20, 'name' => 'BUTON UTARA'],
        ['id' => 272, 'province_id' => 20, 'name' => 'MUNA'],
        ['id' => 273, 'province_id' => 20, 'name' => 'MUNA BARAT'],
        ['id' => 276, 'province_id' => 20, 'name' => 'KONAWE'],
        ['id' => 277, 'province_id' => 20, 'name' => 'KONAWE UTARA'],
        ['id' => 280, 'province_id' => 20, 'name' => 'BOMBANA'],
        ['id' => 281, 'province_id' => 20, 'name' => 'BUTON'],
        ['id' => 282, 'province_id' => 20, 'name' => 'BUTON SELATAN'],
        ['id' => 283, 'province_id' => 20, 'name' => 'BUTON TENGAH'],
        ['id' => 285, 'province_id' => 20, 'name' => 'KOLAKA UTARA'],
        ['id' => 286, 'province_id' => 20, 'name' => 'KONAWE SELATAN'],
        ['id' => 287, 'province_id' => 20, 'name' => 'WAKATOBI'],
        ['id' => 288, 'province_id' => 20, 'name' => 'KONAWE KEPULAUAN'],
        ['id' => 290, 'province_id' => 21, 'name' => 'KUPANG'],
        ['id' => 292, 'province_id' => 21, 'name' => 'SUMBA TENGAH'],
        ['id' => 293, 'province_id' => 21, 'name' => 'BELU'],
        ['id' => 294, 'province_id' => 21, 'name' => 'MALAKA'],
        ['id' => 296, 'province_id' => 21, 'name' => 'ALOR'],
        ['id' => 297, 'province_id' => 21, 'name' => 'TIMOR TENGAH UTARA'],
        ['id' => 298, 'province_id' => 21, 'name' => 'FLORES TIMUR'],
        ['id' => 300, 'province_id' => 21, 'name' => 'SIKKA'],
        ['id' => 301, 'province_id' => 21, 'name' => 'MANGGARAI'],
        ['id' => 308, 'province_id' => 21, 'name' => 'TIMOR TENGAH SELATAN'],
        ['id' => 309, 'province_id' => 21, 'name' => 'ENDE'],
        ['id' => 310, 'province_id' => 21, 'name' => 'NGADA'],
        ['id' => 313, 'province_id' => 21, 'name' => 'SUMBA TIMUR'],
        ['id' => 314, 'province_id' => 21, 'name' => 'SUMBA BARAT'],
        ['id' => 318, 'province_id' => 21, 'name' => 'MANGGARAI BARAT'],
        ['id' => 319, 'province_id' => 21, 'name' => 'MANGGARAI TIMUR'],
        ['id' => 321, 'province_id' => 21, 'name' => 'NAGEKEO'],
        ['id' => 323, 'province_id' => 21, 'name' => 'ROTE NDAO'],
        ['id' => 325, 'province_id' => 21, 'name' => 'SUMBA BARAT DAYA'],
        ['id' => 326, 'province_id' => 21, 'name' => 'LEMBATA'],
        ['id' => 328, 'province_id' => 21, 'name' => 'SABU RAIJUA'],
        ['id' => 330, 'province_id' => 22, 'name' => 'MANADO'],
        ['id' => 331, 'province_id' => 22, 'name' => 'KOTAMOBAGU'],
        ['id' => 332, 'province_id' => 22, 'name' => 'BOLAANG MONGONDOW UTARA'],
        ['id' => 333, 'province_id' => 22, 'name' => 'BOLAANG MONGONDOW'],
        ['id' => 335, 'province_id' => 22, 'name' => 'BOLAANG MONGONDOW SELATAN'],
        ['id' => 336, 'province_id' => 22, 'name' => 'BOLAANG MONGONDOW TIMUR'],
        ['id' => 338, 'province_id' => 22, 'name' => 'KEPULAUAN SANGIHE'],
        ['id' => 339, 'province_id' => 22, 'name' => 'KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)'],
        ['id' => 341, 'province_id' => 22, 'name' => 'MINAHASA'],
        ['id' => 342, 'province_id' => 22, 'name' => 'BITUNG'],
        ['id' => 347, 'province_id' => 22, 'name' => 'KEPULAUAN TALAUD'],
        ['id' => 348, 'province_id' => 22, 'name' => 'MINAHASA UTARA'],
        ['id' => 349, 'province_id' => 22, 'name' => 'MINAHASA SELATAN'],
        ['id' => 351, 'province_id' => 22, 'name' => 'MINAHASA TENGGARA'],
        ['id' => 352, 'province_id' => 22, 'name' => 'TOMOHON'],
        ['id' => 397, 'province_id' => 23, 'name' => 'PADANG'],
        ['id' => 399, 'province_id' => 23, 'name' => 'TANAH DATAR'],
        ['id' => 401, 'province_id' => 23, 'name' => 'BUKITTINGGI'],
        ['id' => 402, 'province_id' => 23, 'name' => 'PASAMAN'],
        ['id' => 404, 'province_id' => 23, 'name' => 'PESISIR SELATAN'],
        ['id' => 405, 'province_id' => 23, 'name' => 'PARIAMAN'],
        ['id' => 406, 'province_id' => 23, 'name' => 'PADANG PARIAMAN'],
        ['id' => 407, 'province_id' => 23, 'name' => 'LIMA PULUH KOTA'],
        ['id' => 408, 'province_id' => 23, 'name' => 'PAYAKUMBUH'],
        ['id' => 410, 'province_id' => 23, 'name' => 'SAWAH LUNTO'],
        ['id' => 411, 'province_id' => 23, 'name' => 'SOLOK'],
        ['id' => 412, 'province_id' => 23, 'name' => 'PADANG PANJANG'],
        ['id' => 413, 'province_id' => 23, 'name' => 'DHARMASRAYA'],
        ['id' => 416, 'province_id' => 23, 'name' => 'KEPULAUAN MENTAWAI'],
        ['id' => 419, 'province_id' => 23, 'name' => 'PASAMAN BARAT'],
        ['id' => 424, 'province_id' => 23, 'name' => 'SOLOK SELATAN'],
        ['id' => 426, 'province_id' => 23, 'name' => 'SIJUNJUNG'],
        ['id' => 427, 'province_id' => 23, 'name' => 'AGAM'],
        ['id' => 428, 'province_id' => 24, 'name' => 'PANGKAL PINANG'],
        ['id' => 429, 'province_id' => 24, 'name' => 'BANGKA'],
        ['id' => 430, 'province_id' => 24, 'name' => 'BANGKA BARAT'],
        ['id' => 431, 'province_id' => 24, 'name' => 'BANGKA TENGAH'],
        ['id' => 432, 'province_id' => 24, 'name' => 'BANGKA SELATAN'],
        ['id' => 596, 'province_id' => 24, 'name' => 'BELITUNG'],
        ['id' => 597, 'province_id' => 24, 'name' => 'BELITUNG TIMUR'],
        ['id' => 433, 'province_id' => 25, 'name' => 'PEKANBARU'],
        ['id' => 434, 'province_id' => 25, 'name' => 'DUMAI'],
        ['id' => 435, 'province_id' => 25, 'name' => 'KAMPAR'],
        ['id' => 436, 'province_id' => 25, 'name' => 'BENGKALIS'],
        ['id' => 438, 'province_id' => 25, 'name' => 'INDRAGIRI HULU'],
        ['id' => 439, 'province_id' => 25, 'name' => 'INDRAGIRI HILIR'],
        ['id' => 441, 'province_id' => 25, 'name' => 'ROKAN HILIR'],
        ['id' => 443, 'province_id' => 25, 'name' => 'KUANTAN SINGINGI'],
        ['id' => 444, 'province_id' => 25, 'name' => 'PELALAWAN'],
        ['id' => 447, 'province_id' => 25, 'name' => 'ROKAN HULU'],
        ['id' => 451, 'province_id' => 25, 'name' => 'SIAK'],
        ['id' => 454, 'province_id' => 25, 'name' => 'KEPULAUAN MERANTI'],
        ['id' => 473, 'province_id' => 26, 'name' => 'PALEMBANG'],
        ['id' => 475, 'province_id' => 26, 'name' => 'MUSI RAWAS'],
        ['id' => 476, 'province_id' => 26, 'name' => 'MUSI RAWAS UTARA'],
        ['id' => 479, 'province_id' => 26, 'name' => 'OGAN KOMERING ULU'],
        ['id' => 480, 'province_id' => 26, 'name' => 'OGAN KOMERING ILIR'],
        ['id' => 482, 'province_id' => 26, 'name' => 'LAHAT'],
        ['id' => 485, 'province_id' => 26, 'name' => 'MUARA ENIM'],
        ['id' => 486, 'province_id' => 26, 'name' => 'PENUKAL ABAB LEMATANG ILIR'],
        ['id' => 487, 'province_id' => 26, 'name' => 'PAGAR ALAM'],
        ['id' => 488, 'province_id' => 26, 'name' => 'PRABUMULIH'],
        ['id' => 489, 'province_id' => 26, 'name' => 'MUSI BANYUASIN'],
        ['id' => 491, 'province_id' => 26, 'name' => 'BANYUASIN'],
        ['id' => 492, 'province_id' => 26, 'name' => 'EMPAT LAWANG'],
        ['id' => 493, 'province_id' => 26, 'name' => 'OGAN ILIR'],
        ['id' => 494, 'province_id' => 26, 'name' => 'OGAN KOMERING ULU TIMUR'],
        ['id' => 495, 'province_id' => 26, 'name' => 'OGAN KOMERING ULU SELATAN'],
        ['id' => 496, 'province_id' => 26, 'name' => 'LUBUK LINGGAU'],
        ['id' => 497, 'province_id' => 27, 'name' => 'PALU'],
        ['id' => 498, 'province_id' => 27, 'name' => 'BANGGAI'],
        ['id' => 499, 'province_id' => 27, 'name' => 'POSO'],
        ['id' => 500, 'province_id' => 27, 'name' => 'TOLI-TOLI'],
        ['id' => 501, 'province_id' => 27, 'name' => 'BANGGAI LAUT'],
        ['id' => 502, 'province_id' => 27, 'name' => 'BANGGAI KEPULAUAN'],
        ['id' => 504, 'province_id' => 27, 'name' => 'BUOL'],
        ['id' => 505, 'province_id' => 27, 'name' => 'DONGGALA'],
        ['id' => 507, 'province_id' => 27, 'name' => 'SIGI'],
        ['id' => 509, 'province_id' => 27, 'name' => 'MOROWALI'],
        ['id' => 510, 'province_id' => 27, 'name' => 'MOROWALI UTARA'],
        ['id' => 511, 'province_id' => 27, 'name' => 'PARIGI MOUTONG'],
        ['id' => 512, 'province_id' => 27, 'name' => 'TOJO UNA-UNA'],
        ['id' => 513, 'province_id' => 28, 'name' => 'PONTIANAK'],
        ['id' => 514, 'province_id' => 28, 'name' => 'KETAPANG'],
        ['id' => 515, 'province_id' => 28, 'name' => 'SANGGAU'],
        ['id' => 516, 'province_id' => 28, 'name' => 'SINGKAWANG'],
        ['id' => 517, 'province_id' => 28, 'name' => 'SINTANG'],
        ['id' => 519, 'province_id' => 28, 'name' => 'KAPUAS HULU'],
        ['id' => 522, 'province_id' => 28, 'name' => 'BENGKAYANG'],
        ['id' => 523, 'province_id' => 28, 'name' => 'LANDAK'],
        ['id' => 524, 'province_id' => 28, 'name' => 'MELAWI'],
        ['id' => 526, 'province_id' => 28, 'name' => 'MEMPAWAH'],
        ['id' => 527, 'province_id' => 28, 'name' => 'KUBU RAYA'],
        ['id' => 528, 'province_id' => 28, 'name' => 'SAMBAS'],
        ['id' => 529, 'province_id' => 28, 'name' => 'SEKADAU'],
        ['id' => 530, 'province_id' => 28, 'name' => 'KAYONG UTARA'],
        ['id' => 546, 'province_id' => 29, 'name' => 'SORONG'],
        ['id' => 547, 'province_id' => 29, 'name' => 'TAMBRAUW'],
        ['id' => 548, 'province_id' => 29, 'name' => 'FAKFAK'],
        ['id' => 549, 'province_id' => 29, 'name' => 'KAIMANA'],
        ['id' => 551, 'province_id' => 29, 'name' => 'RAJA AMPAT'],
        ['id' => 552, 'province_id' => 29, 'name' => 'SORONG SELATAN'],
        ['id' => 553, 'province_id' => 29, 'name' => 'MAYBRAT'],
        ['id' => 554, 'province_id' => 29, 'name' => 'TELUK BINTUNI'],
        ['id' => 556, 'province_id' => 29, 'name' => 'TELUK WONDAMA'],
        ['id' => 557, 'province_id' => 29, 'name' => 'MANOKWARI'],
        ['id' => 558, 'province_id' => 29, 'name' => 'PEGUNUNGAN ARFAK'],
        ['id' => 559, 'province_id' => 29, 'name' => 'MANOKWARI SELATAN'],
        ['id' => 598, 'province_id' => 30, 'name' => 'BANDAR LAMPUNG'],
        ['id' => 599, 'province_id' => 30, 'name' => 'LAMPUNG SELATAN'],
        ['id' => 600, 'province_id' => 30, 'name' => 'LAMPUNG UTARA'],
        ['id' => 601, 'province_id' => 30, 'name' => 'METRO'],
        ['id' => 603, 'province_id' => 30, 'name' => 'LAMPUNG BARAT'],
        ['id' => 604, 'province_id' => 30, 'name' => 'PESISIR BARAT'],
        ['id' => 605, 'province_id' => 30, 'name' => 'LAMPUNG TENGAH'],
        ['id' => 607, 'province_id' => 30, 'name' => 'LAMPUNG TIMUR'],
        ['id' => 608, 'province_id' => 30, 'name' => 'WAY KANAN'],
        ['id' => 609, 'province_id' => 30, 'name' => 'TULANG BAWANG'],
        ['id' => 610, 'province_id' => 30, 'name' => 'MESUJI'],
        ['id' => 611, 'province_id' => 30, 'name' => 'TULANG BAWANG BARAT'],
        ['id' => 615, 'province_id' => 30, 'name' => 'PRINGSEWU'],
        ['id' => 616, 'province_id' => 30, 'name' => 'TANGGAMUS'],
        ['id' => 618, 'province_id' => 30, 'name' => 'PESAWARAN'],
        ['id' => 626, 'province_id' => 31, 'name' => 'TARAKAN'],
        ['id' => 627, 'province_id' => 31, 'name' => 'BULUNGAN'],
        ['id' => 628, 'province_id' => 31, 'name' => 'MALINAU'],
        ['id' => 629, 'province_id' => 31, 'name' => 'NUNUKAN'],
        ['id' => 631, 'province_id' => 31, 'name' => 'TANA TIDUNG'],
        ['id' => 636, 'province_id' => 32, 'name' => 'TERNATE'],
        ['id' => 637, 'province_id' => 32, 'name' => 'HALMAHERA BARAT'],
        ['id' => 639, 'province_id' => 32, 'name' => 'HALMAHERA SELATAN'],
        ['id' => 640, 'province_id' => 32, 'name' => 'HALMAHERA TENGAH'],
        ['id' => 641, 'province_id' => 32, 'name' => 'HALMAHERA TIMUR'],
        ['id' => 642, 'province_id' => 32, 'name' => 'HALMAHERA UTARA'],
        ['id' => 643, 'province_id' => 32, 'name' => 'PULAU MOROTAI'],
        ['id' => 644, 'province_id' => 32, 'name' => 'KEPULAUAN SULA'],
        ['id' => 646, 'province_id' => 32, 'name' => 'PULAU TALIABU'],
        ['id' => 647, 'province_id' => 32, 'name' => 'TIDORE KEPULAUAN'],
        ['id' => 648, 'province_id' => 33, 'name' => 'MAKASSAR'],
        ['id' => 649, 'province_id' => 33, 'name' => 'BANTAENG'],
        ['id' => 650, 'province_id' => 33, 'name' => 'BARRU'],
        ['id' => 651, 'province_id' => 33, 'name' => 'BULUKUMBA'],
        ['id' => 652, 'province_id' => 33, 'name' => 'ENREKANG'],
        ['id' => 653, 'province_id' => 33, 'name' => 'JENEPONTO'],
        ['id' => 654, 'province_id' => 33, 'name' => 'TANA TORAJA'],
        ['id' => 655, 'province_id' => 33, 'name' => 'TORAJA UTARA'],
        ['id' => 659, 'province_id' => 33, 'name' => 'MAROS'],
        ['id' => 663, 'province_id' => 33, 'name' => 'PALOPO'],
        ['id' => 664, 'province_id' => 33, 'name' => 'PINRANG'],
        ['id' => 667, 'province_id' => 33, 'name' => 'SIDENRENG RAPPANG'],
        ['id' => 670, 'province_id' => 33, 'name' => 'WAJO'],
        ['id' => 671, 'province_id' => 33, 'name' => 'SINJAI'],
        ['id' => 673, 'province_id' => 33, 'name' => 'GOWA'],
        ['id' => 674, 'province_id' => 33, 'name' => 'TAKALAR'],
        ['id' => 676, 'province_id' => 33, 'name' => 'BONE'],
        ['id' => 678, 'province_id' => 33, 'name' => 'SOPPENG'],
        ['id' => 679, 'province_id' => 33, 'name' => 'KEPULAUAN SELAYAR'],
        ['id' => 680, 'province_id' => 33, 'name' => 'PANGKAJENE KEPULAUAN'],
        ['id' => 683, 'province_id' => 33, 'name' => 'PAREPARE'],
        ['id' => 684, 'province_id' => 33, 'name' => 'LUWU'],
        ['id' => 685, 'province_id' => 33, 'name' => 'LUWU TIMUR'],
        ['id' => 686, 'province_id' => 33, 'name' => 'LUWU UTARA'],
        ['id' => 657, 'province_id' => 34, 'name' => 'MAMUJU'],
        ['id' => 658, 'province_id' => 34, 'name' => 'MAMUJU TENGAH'],
        ['id' => 662, 'province_id' => 34, 'name' => 'MAJENE'],
        ['id' => 665, 'province_id' => 34, 'name' => 'POLEWALI MANDAR'],
        ['id' => 687, 'province_id' => 34, 'name' => 'MAMASA'],
        ['id' => 688, 'province_id' => 34, 'name' => 'MAMUJU UTARA'],
    ]
];